export const defaultData = [
  {
    id: 148525,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Reddit",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Reddit",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Reddit",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Reddit",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Reddit",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Reddit",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Reddit",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Reddit",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
];
